"""Use Qwen3-VL-Thinking with ``<think>`` generated by the policy."""

from __future__ import annotations


ASSISTANT_PREFIX = "<|im_start|>assistant\n"
_GENERATION_BLOCK = "{%- if add_generation_prompt %}"
_THINKING_PREFILL = "'<|im_start|>assistant\\n<think>\\n'"
_ASSISTANT_ONLY = "'<|im_start|>assistant\\n'"


def configure_thinking_tokenizer(tokenizer) -> None:
    """Remove only the final generation prefill from the Thinking template.

    Past assistant messages retain the model's native template. This must be
    applied to the tokenizer used by the dataset and trajectory collector, and
    to the evaluator's processor tokenizer.
    """

    template = tokenizer.chat_template
    if not isinstance(template, str):
        raise ValueError("Qwen3-VL-Thinking requires a string chat template")
    before, marker, generation = template.rpartition(_GENERATION_BLOCK)
    if not marker or generation.count(_THINKING_PREFILL) != 1:
        raise ValueError(
            "Expected the Qwen3-VL-Thinking generation prefill; "
            "check the model and tokenizer revision"
        )
    tokenizer.chat_template = before + marker + generation.replace(
        _THINKING_PREFILL, _ASSISTANT_ONLY, 1
    )


def apply_thinking_chat_template(tokenizer, messages) -> str:
    """Render a turn and verify that ``<think>`` is not in the prompt suffix."""

    prompt = tokenizer.apply_chat_template(
        messages, add_generation_prompt=True, tokenize=False
    )
    if not isinstance(prompt, str) or not prompt.endswith(ASSISTANT_PREFIX):
        raise ValueError(
            "Thinking prompt must end at the assistant prefix without a prefilled <think>"
        )
    return prompt
